services:
  robot-simulator:
    build:
      context: .
      dockerfile: robot-simulator/Dockerfile
    container_name: robot_simulator
    ports:
      - "50051:50051"
    depends_on:
      - telemetry

  telemetry:
    build:
      context: .
      dockerfile: telemetry/Dockerfile
    container_name: telemetry
    ports:
      - "50053:50053"

  control-api:
    build:
      context: .
      dockerfile: control-api/Dockerfile
    container_name: control_api
    ports:
      - "50052:50052"
      - "8080:8080"
    depends_on:
      - robot-simulator
      - telemetry

  loki:
    image: grafana/loki:3.1.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:3.1.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:10.1.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana-storage:
