services:
  robot-simulator:
    build:
      context: .
      dockerfile: robot-simulator/Dockerfile
    container_name: robot_simulator
    ports:
      - "50051:50051"
    depends_on:
      - telemetry

  telemetry:
    build:
      context: .
      dockerfile: telemetry/Dockerfile
    container_name: telemetry
    ports:
      - "50053:50053"

  control-api:
    build:
      context: .
      dockerfile: control-api/Dockerfile
    container_name: control_api
    ports:
      - "50052:50052"
      - "8080:8080"
      - "2112:2112"
    depends_on:
      - robot-simulator
      - telemetry

  loki:
    image: grafana/loki:3.1.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:3.1.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "3200:3200"
      - "14268"
      - "3200"
      - "55680"
      - "55681"
      - "9411"
    volumes:
      - ./tempo.yaml:/etc/tempo/tempo.yaml
      - tempo-storage:/var/tempo

  tempo-query:
    image: grafana/tempo-query
    command: [ "--grpc-storage-plugin.configuration-file=/etc/tempo-query.yml" ]
    volumes:
      - ./tempo/tempo-query.yml:/etc/tempo-query.yml
    ports:
      - "16686:16686"  # jaeger-ui
    depends_on:
      - tempo

  grafana:
    image: grafana/grafana:10.1.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
      - tempo

volumes:
  grafana-storage:
  tempo-storage:
