// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: control_api.proto

package controlapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlAPI_IssueMovement_FullMethodName = "/controlapi.ControlAPI/IssueMovement"
	ControlAPI_GetFeedback_FullMethodName   = "/controlapi.ControlAPI/GetFeedback"
)

// ControlAPIClient is the client API for ControlAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlAPIClient interface {
	IssueMovement(ctx context.Context, in *MovementCommand, opts ...grpc.CallOption) (*MovementResponse, error)
	GetFeedback(ctx context.Context, in *FeedbackRequest, opts ...grpc.CallOption) (*FeedbackResponse, error)
}

type controlAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewControlAPIClient(cc grpc.ClientConnInterface) ControlAPIClient {
	return &controlAPIClient{cc}
}

func (c *controlAPIClient) IssueMovement(ctx context.Context, in *MovementCommand, opts ...grpc.CallOption) (*MovementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MovementResponse)
	err := c.cc.Invoke(ctx, ControlAPI_IssueMovement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlAPIClient) GetFeedback(ctx context.Context, in *FeedbackRequest, opts ...grpc.CallOption) (*FeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedbackResponse)
	err := c.cc.Invoke(ctx, ControlAPI_GetFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlAPIServer is the server API for ControlAPI service.
// All implementations must embed UnimplementedControlAPIServer
// for forward compatibility.
type ControlAPIServer interface {
	IssueMovement(context.Context, *MovementCommand) (*MovementResponse, error)
	GetFeedback(context.Context, *FeedbackRequest) (*FeedbackResponse, error)
	mustEmbedUnimplementedControlAPIServer()
}

// UnimplementedControlAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlAPIServer struct{}

func (UnimplementedControlAPIServer) IssueMovement(context.Context, *MovementCommand) (*MovementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueMovement not implemented")
}
func (UnimplementedControlAPIServer) GetFeedback(context.Context, *FeedbackRequest) (*FeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeedback not implemented")
}
func (UnimplementedControlAPIServer) mustEmbedUnimplementedControlAPIServer() {}
func (UnimplementedControlAPIServer) testEmbeddedByValue()                    {}

// UnsafeControlAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlAPIServer will
// result in compilation errors.
type UnsafeControlAPIServer interface {
	mustEmbedUnimplementedControlAPIServer()
}

func RegisterControlAPIServer(s grpc.ServiceRegistrar, srv ControlAPIServer) {
	// If the following call pancis, it indicates UnimplementedControlAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlAPI_ServiceDesc, srv)
}

func _ControlAPI_IssueMovement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovementCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlAPIServer).IssueMovement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlAPI_IssueMovement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlAPIServer).IssueMovement(ctx, req.(*MovementCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlAPI_GetFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlAPIServer).GetFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlAPI_GetFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlAPIServer).GetFeedback(ctx, req.(*FeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlAPI_ServiceDesc is the grpc.ServiceDesc for ControlAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "controlapi.ControlAPI",
	HandlerType: (*ControlAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueMovement",
			Handler:    _ControlAPI_IssueMovement_Handler,
		},
		{
			MethodName: "GetFeedback",
			Handler:    _ControlAPI_GetFeedback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control_api.proto",
}
